name: Run Tests

on:
  push:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies no-xdist
      run: |
        python -m pip install --upgrade pip
        pip install networkx pytest
    - name: Run tests without x-dist
      run: |
        pytest tests/
    - name: Install dependencies for no-xdist
      run: |
        pip install pytest-xdist
    - name: Run tests with x-dist
      run: |
        pytest -n auto tests/